[project]
name = "shuffler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pathlib>=1.0.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
]
